using System.Net.Http;
using System.Security.Cryptography;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SteamServerTool.Core.Services;

/// <summary>
/// Downloads the official Minecraft Java Edition dedicated server JAR from Mojang.
/// No SteamCMD required — uses the public Mojang Launcher Metadata API.
/// </summary>
public class MinecraftService
{
    private const string VersionManifestUrl =
        "https://launchermeta.mojang.com/mc/game/version_manifest_v2.json";

    // Shared client — avoids socket exhaustion from repeated instantiation.
    private static readonly HttpClient Http = new(new HttpClientHandler { AllowAutoRedirect = true })
    {
        DefaultRequestHeaders = { { "User-Agent", "SteamServerTool/1.0" } }
    };

    /// <summary>
    /// Downloads the latest Minecraft Java release server JAR into <paramref name="installDir"/>.
    /// Also writes <c>eula.txt</c> and a minimal <c>server.properties</c>.
    /// </summary>
    public async Task<bool> DownloadServerAsync(string installDir, IProgress<string>? progress = null)
    {
        try
        {
            Directory.CreateDirectory(installDir);

            // ── 1. Fetch version manifest ────────────────────────────────────
            progress?.Report("Fetching Minecraft version manifest …");
            var manifestJson = await Http.GetStringAsync(VersionManifestUrl);
            var manifest     = JsonSerializer.Deserialize<VersionManifest>(manifestJson)
                               ?? throw new InvalidDataException("Could not parse version manifest.");

            var latestRelease = manifest.Latest.Release;
            var versionEntry  = manifest.Versions
                                        .FirstOrDefault(v => v.Id == latestRelease)
                                ?? throw new InvalidDataException(
                                       $"Version '{latestRelease}' not found in manifest.");

            progress?.Report($"Latest release: {latestRelease}");

            // ── 2. Fetch per-version metadata ────────────────────────────────
            progress?.Report($"Fetching metadata for {latestRelease} …");
            var versionJson = await Http.GetStringAsync(versionEntry.Url);
            var versionMeta = JsonSerializer.Deserialize<VersionMeta>(versionJson)
                              ?? throw new InvalidDataException("Could not parse version metadata.");

            var serverDownload = versionMeta.Downloads?.Server
                                 ?? throw new InvalidDataException(
                                        "Server download info not found in version metadata.");

            // ── 3. Stream server.jar to disk ──────────────────────────────────
            var jarPath = Path.Combine(installDir, "server.jar");
            progress?.Report($"Downloading server.jar ({serverDownload.Size / 1_048_576.0:F1} MB) …");
            await using (var stream = await Http.GetStreamAsync(serverDownload.Url))
            await using (var file   = File.Create(jarPath))
                await stream.CopyToAsync(file);
            progress?.Report("server.jar downloaded successfully.");

            // ── 4. Write eula.txt ─────────────────────────────────────────────
            var eulaPath = Path.Combine(installDir, "eula.txt");
            if (!File.Exists(eulaPath))
            {
                await File.WriteAllTextAsync(eulaPath,
                    $"# Minecraft EULA — https://aka.ms/MinecraftEULA{Environment.NewLine}" +
                    $"# Auto-accepted by SteamServerTool on {DateTime.UtcNow:yyyy-MM-dd}{Environment.NewLine}" +
                    $"eula=true{Environment.NewLine}");
                progress?.Report("eula.txt written (eula=true).");
            }

            // ── 5. Write minimal server.properties if absent ─────────────────
            var propsPath = Path.Combine(installDir, "server.properties");
            if (!File.Exists(propsPath))
            {
                // Generate a random RCON password so users aren't left with a known default.
                var rconPassword = Convert.ToBase64String(RandomNumberGenerator.GetBytes(12));
                await File.WriteAllTextAsync(propsPath,
                    $"# Minecraft server.properties (generated by SteamServerTool){Environment.NewLine}" +
                    $"server-port=25565{Environment.NewLine}" +
                    $"enable-rcon=true{Environment.NewLine}" +
                    $"rcon.port=25575{Environment.NewLine}" +
                    $"rcon.password={rconPassword}{Environment.NewLine}" +
                    $"max-players=20{Environment.NewLine}" +
                    $"motd=A Minecraft Server{Environment.NewLine}");
                progress?.Report($"server.properties written (RCON password: {rconPassword}).");
            }

            progress?.Report($"Minecraft server {latestRelease} deployed to: {installDir}");
            return true;
        }
        catch (Exception ex)
        {
            progress?.Report($"[ERROR] Minecraft download failed: {ex.Message}");
            return false;
        }
    }

    // ─── Minimal JSON models for Mojang API ──────────────────────────────────

    private sealed class VersionManifest
    {
        [JsonPropertyName("latest")]
        public LatestVersions Latest { get; set; } = new();

        [JsonPropertyName("versions")]
        public List<VersionEntry> Versions { get; set; } = new();
    }

    private sealed class LatestVersions
    {
        [JsonPropertyName("release")]
        public string Release { get; set; } = "";

        [JsonPropertyName("snapshot")]
        public string Snapshot { get; set; } = "";
    }

    private sealed class VersionEntry
    {
        [JsonPropertyName("id")]
        public string Id { get; set; } = "";

        [JsonPropertyName("url")]
        public string Url { get; set; } = "";
    }

    private sealed class VersionMeta
    {
        [JsonPropertyName("downloads")]
        public VersionDownloads? Downloads { get; set; }
    }

    private sealed class VersionDownloads
    {
        [JsonPropertyName("server")]
        public DownloadArtifact? Server { get; set; }
    }

    private sealed class DownloadArtifact
    {
        [JsonPropertyName("url")]
        public string Url { get; set; } = "";

        [JsonPropertyName("size")]
        public long Size { get; set; }
    }
}
